CREATE TABLE IF NOT EXISTS users (
	user_id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_name TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	create_at TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime'))
);


CREATE TABLE IF NOT EXISTS tweets (
	tweet_id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL, 
	message TEXT NOT NULL,
	create_at TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime'))
);


CREATE TABLE IF NOT EXISTS follows (
	follow_id INTEGER NOT NULL,
	followee_id INTEGER NOT NULL
);


CREATE TABLE IF NOT EXISTS comments (
	comment_id INTEGER PRIMARY KEY AUTOINCREMENT,
	tweet_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL, 
	message TEXT NOT NULL,
	create_at TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime'))
);